PORTNAME=       fidistat
PORTVERSION=    2.0.2
CATEGORIES=     local

MAINTAINER=     nudelfabrik@fourtytwo.xyz

USE_GITHUB=     yes
GH_ACCOUNT=     nudelfabrik
GH_PROJECT=     FidiStat


.include <bsd.port.mk>
